spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/MyAppRealm/
          jwk-set-uri: http://localhost:9090/realms/MyAppRealm/protocol/openid-connect/certs


logging:
  level:
    org.springframework.security: DEBUG